# Site settings
title: ModernTLD
site: Cesium
description: > # this means to ignore newlines until "baseurl:"
    Cesium is a domain registry system created for use on the OpenNIC Network
    for ModernTLD and the .o Top-Level Domain.
baseurl: ""
paginate: 5
paginate_path: "/page:num/"
color:
    main: "blue-grey"
    navbar: "blue-grey"
    chips: "orange"
    footer: "teal"
owner:
    email: cesium@moderntld.com
    facebook:
        show: false
        name: "ModernTLD"
        url: "n/a"
    github:
        show: true
        username: "ModernTLD"
    twitter:
        show: false
        username: "ModernTLD"
    disqus:
        show: false
        username: "jonaharagon"
sass:
    sass_dir: _sass
    style: compressed
permalink: pretty
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-feed
    - jekyll-paginate
